Repository mujik-tigers/dowith, pull requests merged in 2024-07, with the labels that each got.

#8 feat: 사용자 회원가입 시 발생하는 예외를 처리하는 기능 구현 완료
  .gitignore
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/MemberRegisterException.java
  src/test/java/com/dowe/DoweApplicationTests.java
  src/test/java/com/dowe/IntegrationTestSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/member/MemberRepositoryTest.java
Labels: new feature, test

#7 AuthController, TokenManager, OAuthProvider 기능 및 테스트 코드 작성
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/application/OAuthProvider.java
  src/main/java/com/dowe/auth/application/TokenManager.java
  src/main/java/com/dowe/auth/dto/AccessToken.java
  src/main/java/com/dowe/auth/dto/UserResource.java
  src/main/java/com/dowe/config/converter/ProviderConverter.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/auth/ExpiredTokenException.java
  src/main/java/com/dowe/exception/auth/InvalidAuthorizationCodeException.java
  src/main/java/com/dowe/exception/auth/InvalidProviderException.java
  src/main/java/com/dowe/util/AppConstants.java
  src/test/java/com/dowe/IntegrationTestSupport.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/OAuthProviderTest.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
Labels: documentation, new feature, test

#6 feat: OAuth 인증 기능 구현 완료
  .github/workflows/auto-deploy.yml
  .github/workflows/test-report.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dowe/auth/MemberToken.java
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/application/OAuthProvider.java
  src/main/java/com/dowe/auth/application/TokenManager.java
  src/main/java/com/dowe/auth/dto/AccessToken.java
  src/main/java/com/dowe/auth/dto/LoginData.java
  src/main/java/com/dowe/auth/dto/TokenPair.java
  src/main/java/com/dowe/auth/dto/UserResource.java
  src/main/java/com/dowe/auth/infrastructure/MemberTokenRepository.java
  src/main/java/com/dowe/auth/presentation/AuthController.java
  src/main/java/com/dowe/config/PropertiesConfig.java
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/config/converter/ProviderConverter.java
  src/main/java/com/dowe/config/properties/JwtProperties.java
  src/main/java/com/dowe/config/properties/OAuthProperties.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/MemberRegisterException.java
  src/main/java/com/dowe/exception/auth/ExpiredTokenException.java
  src/main/java/com/dowe/exception/auth/InvalidAuthorizationCodeException.java
  src/main/java/com/dowe/exception/auth/InvalidProviderException.java
  src/main/java/com/dowe/member/Member.java
  src/main/java/com/dowe/member/MemberRepository.java
  src/main/java/com/dowe/member/Provider.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/RandomUtil.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/resources/schema.sql
  src/test/java/com/dowe/DoweApplicationTests.java
  src/test/java/com/dowe/IntegrationTestSupport.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/auth/application/OAuthProviderTest.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/member/MemberRepositoryTest.java
Labels: new feature

#10 Release: 로그인 로직 기능 배포
  .github/workflows/auto-deploy.yml
  .github/workflows/test-report.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/docinfo.html
  src/docs/asciidoc/index.adoc
  src/main/java/com/dowe/auth/MemberToken.java
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/application/OAuthProvider.java
  src/main/java/com/dowe/auth/application/TokenManager.java
  src/main/java/com/dowe/auth/dto/AccessToken.java
  src/main/java/com/dowe/auth/dto/LoginData.java
  src/main/java/com/dowe/auth/dto/TokenPair.java
  src/main/java/com/dowe/auth/dto/UserResource.java
  src/main/java/com/dowe/auth/infrastructure/MemberTokenRepository.java
  src/main/java/com/dowe/auth/presentation/AuthController.java
  src/main/java/com/dowe/config/PropertiesConfig.java
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/config/converter/ProviderConverter.java
  src/main/java/com/dowe/config/properties/JwtProperties.java
  src/main/java/com/dowe/config/properties/OAuthProperties.java
  src/main/java/com/dowe/exception/CustomException.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/MemberRegisterException.java
  src/main/java/com/dowe/exception/auth/ExpiredTokenException.java
  src/main/java/com/dowe/exception/auth/InvalidAuthorizationCodeException.java
  src/main/java/com/dowe/exception/auth/InvalidProviderException.java
  src/main/java/com/dowe/member/Member.java
  src/main/java/com/dowe/member/MemberRepository.java
  src/main/java/com/dowe/member/Provider.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/RandomUtil.java
  src/main/java/com/dowe/util/api/ApiResponse.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/resources/schema.sql
  src/test/java/com/dowe/DoweApplicationTests.java
  src/test/java/com/dowe/IntegrationTestSupport.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/auth/application/OAuthProviderTest.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/member/MemberRepositoryTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: release

#12 test: 동시성 문제로 발생하는 예외 처리 확인을 위한 테스트 작성 완료
  .github/workflows/auto-deploy.yml
  .github/workflows/test-report.yml
  build.gradle
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/dto/LoginData.java
  src/main/java/com/dowe/config/RedisConfig.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/member/MemberRegisterException.java
  src/main/java/com/dowe/member/application/MemberCodeStorage.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/infrastructure/MemberRepository.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/Initializer.java
  src/main/resources/schema.sql
  src/main/resources/script/save-member-code-if-unique.lua
  src/test/java/com/dowe/IntegrationTestSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/dowe/member/application/MemberCodeStorageTest.java
  src/test/java/com/dowe/member/infrastructure/MemberRepositoryTest.java
Labels: test

#13 Relese: 로그인 로직 변경 사항 배포
  .github/workflows/auto-deploy.yml
  .github/workflows/test-report.yml
  build.gradle
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/dto/LoginData.java
  src/main/java/com/dowe/config/RedisConfig.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/member/MemberRegisterException.java
  src/main/java/com/dowe/member/application/MemberCodeStorage.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/infrastructure/MemberRepository.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/Initializer.java
  src/main/resources/schema.sql
  src/main/resources/script/save-member-code-if-unique.lua
  src/test/java/com/dowe/IntegrationTestSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/dowe/member/application/MemberCodeStorageTest.java
  src/test/java/com/dowe/member/infrastructure/MemberRepositoryTest.java
Labels: release

#14 feat: 인가 로직 구현
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/application/TokenManager.java
  src/main/java/com/dowe/auth/presentation/AuthController.java
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/auth/ExpiredTokenException.java
  src/main/java/com/dowe/exception/auth/InvalidTokenException.java
  src/main/java/com/dowe/exception/auth/TokenException.java
  src/main/java/com/dowe/exception/auth/TokenType.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/java/com/dowe/util/interceptor/LoginInterceptor.java
  src/main/java/com/dowe/util/resolver/Login.java
  src/main/java/com/dowe/util/resolver/LoginArgumentResolver.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
Labels: new feature

#17 test: 토큰 refresh 관련 테스트 구현
  src/docs/asciidoc/api/auth.adoc
  src/main/java/com/dowe/auth/MemberToken.java
  src/main/java/com/dowe/auth/TokenType.java
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/application/TokenManager.java
  src/main/java/com/dowe/auth/presentation/AuthController.java
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/auth/ExpiredTokenException.java
  src/main/java/com/dowe/exception/auth/InvalidAuthorizationHeaderException.java
  src/main/java/com/dowe/exception/auth/InvalidTokenException.java
  src/main/java/com/dowe/exception/auth/TokenException.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/java/com/dowe/util/interceptor/AccessTokenInterceptor.java
  src/main/java/com/dowe/util/interceptor/AuthorizationHeaderInterceptor.java
  src/main/java/com/dowe/util/resolver/Login.java
  src/main/java/com/dowe/util/resolver/LoginArgumentResolver.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/exception/GlobalExceptionHandlerTest.java
Labels: documentation, test, refactor

#18 Release: 인가 로직 배포
  src/docs/asciidoc/api/auth.adoc
  src/main/java/com/dowe/auth/MemberToken.java
  src/main/java/com/dowe/auth/TokenType.java
  src/main/java/com/dowe/auth/application/AuthService.java
  src/main/java/com/dowe/auth/application/TokenManager.java
  src/main/java/com/dowe/auth/presentation/AuthController.java
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/GlobalExceptionHandler.java
  src/main/java/com/dowe/exception/auth/ExpiredTokenException.java
  src/main/java/com/dowe/exception/auth/InvalidAuthorizationHeaderException.java
  src/main/java/com/dowe/exception/auth/InvalidTokenException.java
  src/main/java/com/dowe/exception/auth/TokenException.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/java/com/dowe/util/interceptor/AccessTokenInterceptor.java
  src/main/java/com/dowe/util/interceptor/AuthorizationHeaderInterceptor.java
  src/main/java/com/dowe/util/resolver/Login.java
  src/main/java/com/dowe/util/resolver/LoginArgumentResolver.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/TokenManagerTest.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/exception/GlobalExceptionHandlerTest.java
Labels: release

#20 feat: 이름 변경 기능 구현 완료
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/member/Member.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/dto/MemberName.java
  src/main/java/com/dowe/member/presentation/MemberController.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/java/com/dowe/util/resolver/LoginArgumentResolver.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/auth/application/OAuthProviderTest.java
  src/test/java/com/dowe/member/application/MemberServiceTest.java
  src/test/java/com/dowe/member/presentation/MemberControllerTest.java
Labels: documentation, new feature, test

#22 Release: 이름 변경 기능 배포
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dowe/config/WebConfig.java
  src/main/java/com/dowe/member/Member.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/dto/MemberName.java
  src/main/java/com/dowe/member/presentation/MemberController.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/java/com/dowe/util/resolver/LoginArgumentResolver.java
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/application/AuthServiceTest.java
  src/test/java/com/dowe/auth/application/OAuthProviderTest.java
  src/test/java/com/dowe/member/application/MemberServiceTest.java
  src/test/java/com/dowe/member/presentation/MemberControllerTest.java
Labels: release
