Repository mujik-tigers/dowith, pull requests merged in 2024-08, with the labels that each got.

#24 Release: 워크 스페이스 생성 기능 배포
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/team.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dowe/config/PropertiesConfig.java
  src/main/java/com/dowe/config/S3Config.java
  src/main/java/com/dowe/config/properties/S3Properties.java
  src/main/java/com/dowe/exception/ErrorType.java
  src/main/java/com/dowe/exception/member/MemberNotFoundException.java
  src/main/java/com/dowe/exception/team/AlreadyInTeamException.java
  src/main/java/com/dowe/exception/team/TeamFullException.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/profile/Profile.java
  src/main/java/com/dowe/profile/infrastructure/ProfileRepository.java
  src/main/java/com/dowe/team/Team.java
  src/main/java/com/dowe/team/application/TeamService.java
  src/main/java/com/dowe/team/dto/Manager.java
  src/main/java/com/dowe/team/dto/NewTeam.java
  src/main/java/com/dowe/team/dto/TeamSettings.java
  src/main/java/com/dowe/team/infrastructure/TeamRepository.java
  src/main/java/com/dowe/team/presentation/TeamController.java
  src/main/java/com/dowe/util/AppConstants.java
  src/main/java/com/dowe/util/RandomUtil.java
  src/main/java/com/dowe/util/S3Uploader.java
  src/main/java/com/dowe/util/StringUtil.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/resources/schema.sql
  src/test/java/com/dowe/RestDocsSupport.java
  src/test/java/com/dowe/auth/presentation/AuthControllerTest.java
  src/test/java/com/dowe/team/presentation/TeamControllerTest.java
Labels: release

#28 feat: 생성 시간, 수정 시간을 지닌 `BaseEntity` 추가
  src/main/java/com/dowe/config/JpaAuditingConfig.java
  src/main/java/com/dowe/util/BaseEntity.java
Labels: new feature

#30 release: 생성 시간, 수정 시간을 지닌 `BaseEntity` 추가 배포
  src/main/java/com/dowe/config/JpaAuditingConfig.java
  src/main/java/com/dowe/util/BaseEntity.java
Labels: release

#32 feat: `TodoList` 엔티티 추가
  src/main/java/com/dowe/todolist/TodoList.java
  src/main/resources/schema.sql
Labels: new feature

#33 feat: `TodoList` 엔티티 추가
  src/main/java/com/dowe/todolist/TodoList.java
  src/main/resources/schema.sql
Labels: release

#34 feat: 나의 팀 목록 조회 기능 구현 완료
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/dto/MyTeamList.java
  src/main/java/com/dowe/member/dto/TeamInList.java
  src/main/java/com/dowe/member/presentation/MemberController.java
  src/main/java/com/dowe/team/infrastructure/TeamRepository.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/test/java/com/dowe/member/presentation/MemberControllerTest.java
Labels: documentation, new feature

#35 release: 나의 팀 목록 조회 기능 배포
  src/docs/asciidoc/api/member.adoc
  src/main/java/com/dowe/auth/application/OAuthProvider.java
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/dto/MyTeamList.java
  src/main/java/com/dowe/member/dto/TeamInList.java
  src/main/java/com/dowe/member/presentation/MemberController.java
  src/main/java/com/dowe/team/infrastructure/TeamRepository.java
  src/main/java/com/dowe/util/api/ResponseResult.java
  src/main/java/com/dowe/util/interceptor/AccessTokenInterceptor.java
  src/test/java/com/dowe/member/presentation/MemberControllerTest.java
Labels: release

#37 refactor: `사용자 팀 목록 조회` API 수정을 위한 코드 수정
  src/main/java/com/dowe/member/application/MemberService.java
  src/main/java/com/dowe/member/dto/TeamOutline.java
  src/main/java/com/dowe/member/dto/response/FetchMyTeamResponse.java
  src/main/java/com/dowe/member/presentation/MemberController.java
  src/test/java/com/dowe/member/presentation/MemberControllerTest.java
Labels: refactor
